name: movie_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  freezed_annotation: ^2.4.1
  go_router: ^13.0.1
  carousel_slider: ^4.2.1
  google_sign_in: ^6.1.6
  dio: ^5.4.0
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7
  freezed: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
      - family: mohave
        fonts:
        - asset: assets/Fonts/mohave/Mohave-Bold.ttf
          weight: 700
        - asset: assets/Fonts/mohave/Mohave-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/Fonts/mohave/Mohave-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/Fonts/mohave/Mohave-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/Fonts/mohave/Mohave-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/Fonts/mohave/Mohave-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/Fonts/mohave/Mohave-Light.ttf
          weight: 300
        - asset: assets/Fonts/mohave/Mohave-Regular.ttf
          weight: 400
        - asset: assets/Fonts/mohave/Mohave-Medium.ttf
          weight: 500
        - asset: assets/Fonts/mohave/Mohave-SemiBold.ttf
          weight: 600


