// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB2VkY5XjACdOqiSkVo4qh_6OTe7tRWtE',
    appId: '1:797593040169:web:2a452a199db322a30bf338',
    messagingSenderId: '797593040169',
    projectId: 'movie-app-76a13',
    authDomain: 'movie-app-76a13.firebaseapp.com',
    storageBucket: 'movie-app-76a13.appspot.com',
    measurementId: 'G-XJBYDC3NT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeD9QESC1K_IbCJfsLZV8bEjMk6KhZ8Sc',
    appId: '1:797593040169:android:070ae27b0363effb0bf338',
    messagingSenderId: '797593040169',
    projectId: 'movie-app-76a13',
    storageBucket: 'movie-app-76a13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOFjo3GSHDUpGRc4uSH0oEEETOL0Qgbs4',
    appId: '1:797593040169:ios:bbb79e1a6cef6fec0bf338',
    messagingSenderId: '797593040169',
    projectId: 'movie-app-76a13',
    storageBucket: 'movie-app-76a13.appspot.com',
    androidClientId: '797593040169-nubr3fo3agc8emf307oga1vv8cjrcaek.apps.googleusercontent.com',
    iosClientId: '797593040169-m2vv5m6d1c2rf8daqt0h39p9pkdhtr7o.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieApp',
  );
}
